language: node_js
node_js:
  - "6"
install:
  - yarn
script:
  - yarn test && yarn build
after_success: 'yarn coveralls'  
deploy:
  overwrite: true
  provider: releases
  api_key: 
    secure: tpUMBbaf4ejc4W8I+U6GjLizuw6sT0GmSoCxbNqTxszAnbGSjPorBwX7s9HLgB6tgWpJO/dTUpwhOQzwCTz2nOz+csES/Rj+HAIIO7Y262s46u1AoNNg+xwckNYlDaeq5n8ttGG6F3Z2xLMaAGJgHtIaHt2d0nt14wQ57wTTNKIsKEfUFIkMLOUlMw75PU9vHUcDdsDNiC7Vx4arFg8EHKwAKqxoA5+wPcGvaKspKMiyuE22A0/NyScD61JAMDN0tHgZZrSb0oYTyRsjE1acvt5JWUOyLWopIYqDS8YzaVvh+yUEBLvZ3GPOOxbcpFHCsvIF4fXr5N1P8m80inQ+79rPx9VMtRYzaty3ClvQUm4euhPkmutTcHvxvUjkRdNQfYlNZo8c3zLKL1qvSXbQNmQ6WIpn9JnpSO0zvtyImziboeTFK1bAbuABZB1jUcM5oIIcut5nUcEkfwNY8qfgbjvkG2Tf8ORnMVsyFWoQPwVcZSQ3cP0gmsawuhw0YnczssBolLPYATQvBEGCfXSUmPDW3k/M/fqjH238kTJsqV6SJLtJM/ayIZzRMF/zhOOjSZwsNB3SBPqZMX76RXIShrgeCdwp3fo5pveWDkEObgV0oXP0H7mnd2IQgqdhEQybvyMcIomF3oW+DyL6CADU3cHx5JTgV6Lp9KoY7kx6bsM=
  file:
    - "dist/swiper.css"
    - "dist/swiper.js"
  skip_cleanup: true
  on:
    tags: true
    repo: fex-team/swiper    
    all_branches: true