language: node_js
node_js:
  - "6"
install:
  - yarn
script:
  - yarn test && yarn build
after_success: 'yarn coveralls'  
deploy:
  overwrite: true
  provider: releases
  api_key: 
    secure: bnOzfScwLwAuV7CTVobd3e/6Pl0gEiCCCO7ZXycI8sx4U82QwlGHtumhB0TBsD6/kk1DIcAettgZCNW4Ndf1oEnjnp2J1yHOHyrL14HYX4RbGdfHnXQEy6nhtHgyhmOi0DnrvJrnSex8j3tqhhbQL8KepxUpoEQyScXbh6pA2iY+IGFrr84unYZptcChnzyG3pRmnK7dat809SLM52rZlPTrXhu+ud+8o/diE18WTVdAZ89OBwSPWsLGwuIUtjMnN6GiNssqavceojPA75R+17/9+7TkX0VuIGXOJZ4GfqQT++qAg5kvrvZCuMVQNy947ACfwJqEpyjLMMu9/D4vvpvl6Sw/dC1ytHgkKHQgx5u3O6Crcq4o3YJ6pIt2QSBA2PqWUD0PN7GZFqXiaveH6Kin/TJuZmPHNZ05imMO44GlU+rYX67+WAtzo0RCx9d74Jf3wEpeDAbyYP7ti5Uc1aupd+4MT3at6kPe8blcImy1gxRxLtbBlPGee2Y/CmYwUaRvdHLw2h3BfoXFS2i9CK+UVF28Gak9YUsIVuRYDqXNNjpA30EzS7CLMziQ92qR2e/zE7yfzt4Zudfl7BDgB8uDqtUq+qrBIefTRF/8wuy6frb3AMsrFGnX2FTjJCscBwgq99ekM7+c2/RNtp8pkrRYPcq9j4sv6maiGLPvhk8=
  file:
    - "dist/swiper.css"
    - "dist/swiper.js"
  skip_cleanup: true
  on:
    branch: master
    condition: TRAVIS_REPO_SLUG = fex-team/swiper